### ISSUE TITLE
Decompression Error for most recent whosonfirst-data-latest.db.bz2 file

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/go-whosonfirst-dist#12]
Per @TariqAHassan: 

Attempts to unpack the latest `whosonfirst-data-latest.db.bz2` file fail.

On Ubuntu, this can be replicated by running:

```
wget https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2 \
 && bzip2 -dk whosonfirst-data-latest.db.bz2
```

The full error is the following:

```
bzip2: Data integrity error when decompressing.
        Input file = /path/goes/here, output file = /path/goes/here

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

bzip2: Deleting output file /path/goes/here, if it exists.
```

See: https://github.com/whosonfirst-data/whosonfirst-data/issues/1604

**Comment by TariqAHassan** [comment]
@stepps00 

The unzip operation now works against latest `whosonfirst-data-latest.db.bz2` file.

**Comment by stepps00** [comment]
Great, thanks for the note! I'll close this issue, but please let us know if you experience the issue again.
