### ISSUE TITLE
Support alt files

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-dist#15]
Blocked on: 

https://github.com/whosonfirst/go-whosonfirst-geojson-v2/issues/5

**Comment by nvkelso** [comment]
See also: https://github.com/whosonfirst/go-whosonfirst-geojson-v2/issues/6

**Comment by missinglink** [comment]
Heya, I stumbled on this via https://github.com/whosonfirst/go-whosonfirst-dist#combined-distributions, the two linked issues are now marked as 'closed', does that mean this is now fixed?
